[package]
name = "lower_blir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blir = { path = "../blir" }
patmat = { path = "../patmat" }
blirssa = { path = "../blirssa" }
rand = "0.8.4"
errors = { path = "../errors" }